// <auto-generated />
namespace n01625423_Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hotelData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hotelData));
        
        string IMigrationMetadata.Id
        {
            get { return "202402032111227_hotelData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
